version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: your-app-image
        container_name: your-app-container
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./php.ini:/usr/local/etc/php/php.ini
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: your-webserver-container
        restart: unless-stopped
        ports:
            - "8081:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

    db:
        image: mysql:5.7
        container_name: your-db-container
        restart: unless-stopped
        environment:
            MYSQL_DATABASE:  ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network
        ports:
            - ${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
